# -*- coding: utf-8 -*-
"""Configuracion base y perfiles runtime para inference en Jetson."""

import logging

logger = logging.getLogger(__name__)


CONFIG = {
    "detector_model": "models/plate_detector_best.pt",
    "detector_fallback_model": "models/plate_detector_best.pt",
    "enable_detector_fallback": True,
    "ocr_model": "models/ocr_crnn.tflite",
    "ocr_engine": "rapidocr-lpr",
    "ocr_simple_fallback_to_model": True,
    "ocr_paddle_lang": "latin",
    "ocr_paddle_use_angle_cls": False,
    "ocr_paddle_cls": False,
    "ocr_paddle_det": False,
    "ocr_paddle_show_log": False,
    "ocr_rapid_min_conf": 0.20,
    "ocr_plate_postprocess_enabled": True,
    "ocr_plate_postprocess_strict": True,
    "confidence_threshold": 0.8,
    "fallback_confidence_threshold": 0.20,
    "detector_preprocess_enabled": True,
    "detector_preprocess_clahe_clip": 2.4,
    "iou_threshold": 0.5,
    "input_size": 416,
    "yolo_imgsz": 640,
    "min_area_ratio": 0.002,
    "min_area_ratio_small": 0.0006,
    "max_area_ratio": 1.0,
    "min_aspect_ratio": 0.25,
    "max_aspect_ratio": 8.0,
    "plate_box_scale": 1.0,
    "ocr_box_scale": 0.95,
    "ocr_aware_box_selection": True,
    "prefer_fallback_for_ocr": True,
    "ocr_score_text_weight": 0.75,
    "ocr_score_det_weight": 0.25,
    "ocr_score_fallback_bonus": 0.02,
    "ocr_second_pass_7char_enabled": True,
    "ocr_second_pass_conf_threshold": 0.085,
    "ocr_second_pass_pattern_bonus": 0.16,
    "ctc_len_bonus": 0.12,
    "ctc_len7_bonus": 0.08,
    "ctc_pattern_bonus": 0.25,
    "ctc_no_digit_penalty": 0.15,
    "ctc_no_letter_penalty": 0.15,
    "ctc_vs_char_margin": 0.02,
    "ocr_profile": "balanced",
    "ocr_far_plate_threshold": 160,
    "ocr_far_plate_upscale": 3.0,
    "ocr_far_plate_upscale_threshold": 90,
    "ocr_far_plate_clahe_clip": 6.0,
    "ocr_far_num_chars_min": 5,
    "ocr_far_num_chars_max": 9,
    "ocr_far_char_conf_threshold": 0.25,
    "ocr_far_plate_denoise": True,
    "ocr_far_plate_morph": True,
    "enable_small_plate_rescue": True,
    "small_plate_rescue_only_on_miss": True,
    "small_plate_rescue_upscale": 1.8,
    "small_plate_rescue_imgsz": 960,
    "small_plate_rescue_conf": 0.08,
    "small_plate_rescue_iou": 0.5,
    "small_plate_rescue_accept_conf": 0.20,
    "small_plate_rescue_tiling": True,
    "small_plate_rescue_tile_grid": 2,
    "small_plate_rescue_tile_overlap": 0.22,
    "camera_small_rescue_every_n_detections": 4,
    "camera_small_rescue_only_when_no_live": True,
    "ocr_small_plate_threshold": 100,
    "ocr_small_plate_upscale": 2.0,
    "ocr_small_plate_upscale_threshold": 50,
    "ocr_small_plate_clahe_clip": 4.0,
    "ocr_small_plate_denoise": True,
    "ocr_small_plate_morph": True,
    "ocr_char_topk": 3,
    "ocr_plate_pattern_bonus": 0.22,
    "ocr_plate_hyphen_bonus": 0.08,
    "ocr_plate_beam_width": 24,
    "ocr_pos_correction_enabled": True,
    "ocr_pos_confusion_mix": 0.45,
    "ocr_pos_low_conf_threshold": 0.30,
    "ocr_pos_max_changes": 3,
    "ocr_pos_last_letter_xc_swap": True,
    "ocr_pos_last_digit_24_swap": True,
    "ocr_box_scale_close": 0.78,
    "ocr_box_scale_medium": 0.88,
    "ocr_box_scale_small": 0.95,
    # Aumentado bias vertical para OCR: desplaza ROI hacia abajo para evitar encabezados
    "ocr_roi_y_bias_close": 0.30,
    "ocr_roi_y_bias_medium": 0.20,
    "ocr_roi_y_bias_small": 0.12,
    "ocr_tesseract_cmd": r"C:\Program Files\Tesseract-OCR\tesseract.exe",
    "fps_buffer_size": 30,
    "camera_index": 0,
    "camera_stop_on_plate": False,
    "camera_preview_width": 800,
    "camera_display_width": 800,
    "camera_detection_stride": 2,
    "camera_adaptive_stride_enabled": False,
    "camera_adaptive_stride_target_fps": 8.0,
    "camera_adaptive_stride_update_sec": 2.0,
    "camera_adaptive_stride_min": 1,
    "camera_adaptive_stride_max": 12,
    "camera_motion_skip_enabled": False,
    "camera_motion_skip_threshold": 1.2,
    "camera_motion_skip_max_frames": 8,
    "camera_trigger_confidence": 0.20,
    "camera_ocr_trigger_confidence": 0.20,
    "camera_debug_min_confidence": 0.01,
    "camera_ocr_cooldown_sec": 0.9,
    "camera_ocr_max_pending": 2,
    "camera_ocr_settle_sec": 0.25,
    "camera_ocr_roi_candidates_max": 2,
    "camera_ocr_use_worker": True,
    "camera_ocr_use_detector_box": True,
    "camera_ocr_detector_box_expand": 1.18,
    "camera_ocr_bottom_band_enabled": False,
    "camera_ocr_upscale_enabled": True,
    "camera_ocr_upscale_min_height": 140,
    "camera_ocr_upscale_min_width": 420,
    "camera_ocr_upscale_max_scale": 2.5,
    "camera_ocr_enhance_enabled": True,
    "camera_ocr_enhance_clahe_clip": 2.8,
    "camera_ocr_enhance_sigma": 1.0,
    "camera_ocr_enhance_unsharp_amount": 1.7,
    "camera_ocr_bottom_band_top_ratio": 0.36,
    "camera_ocr_bottom_band_deep_top_ratio": 0.52,
    "camera_ocr_bottom_band_min_height": 22,
    "camera_ocr_header_penalty": 0.55,
    "camera_ocr_alpha_only_penalty": 0.30,
    "camera_ocr_plate3_bonus": 0.20,
    "camera_ocr_plate4_bonus": 0.10,
    "camera_ocr_temporal_vote_enabled": False,
    "camera_ocr_vote_window": 4,
    "camera_ocr_vote_min_hits": 2,
    "camera_ocr_vote_max_age_sec": 4.0,
    "camera_ocr_vote_force_accept_conf": 0.74,
    "ocr_rapid_max_variants": 2,
    "camera_debug_ocr_enabled": False,
    "camera_dump_ocr_input_enabled": False,
    "camera_dump_ocr_input_only": False,
    "camera_debug_ocr_interval_sec": 10.0,
    "camera_debug_ocr_dir": "outputs/ocr_debug",
    "camera_debug_max_pending": 1,
    "camera_plate_capture_enabled": False,
    "camera_plate_capture_dir": "outputs/plate_captures",
    "camera_plate_capture_cooldown_sec": 2.0,
    "camera_plate_capture_same_text_cooldown_sec": 6.0,
    "camera_plate_capture_min_ocr_conf": 0.45,
    "camera_plate_capture_include_ocr_box": True,
    "camera_freeze_timeout_sec": 1.8,
    "camera_reconnect_backoff_sec": 0.35,
    "camera_input_grayscale": False,
    "camera_capture_width": 1280,
    "camera_capture_height": 720,
    "camera_capture_fps": 30,
    "use_gpu": True,
    "show_window": True,
}


def apply_runtime_profile(config, profile_name):
    profile = str(profile_name or "current").lower()
    if profile in ("current", "default"):
        return

    if profile == "jetson-stable":
        config.update({
            "yolo_imgsz": 512,
            "camera_detection_stride": 3,
            "camera_preview_width": 640,
            "camera_display_width": 720,
            "camera_ocr_cooldown_sec": 1.1,
            "camera_ocr_max_pending": 1,
            "camera_ocr_settle_sec": 0.30,
            "enable_detector_fallback": False,
            "enable_small_plate_rescue": False,
            "ocr_second_pass_7char_enabled": False,
        })
        logger.info("Perfil aplicado: jetson-stable")
        return

    if profile == "jetson-quality":
        config.update({
            "yolo_imgsz": 640,
            "camera_detection_stride": 2,
            "camera_preview_width": 800,
            "camera_display_width": 800,
            "camera_ocr_cooldown_sec": 0.9,
            "camera_ocr_max_pending": 2,
            "camera_ocr_settle_sec": 0.22,
            "enable_detector_fallback": True,
            "enable_small_plate_rescue": True,
            "ocr_second_pass_7char_enabled": True,
        })
        logger.info("Perfil aplicado: jetson-quality")
        return

    if profile == "jetson-production":
        config.update({
            "yolo_imgsz": 512,
            "camera_detection_stride": 2,
            "camera_preview_width": 720,
            "camera_display_width": 720,
            "camera_ocr_cooldown_sec": 0.55,
            "camera_ocr_max_pending": 1,
            "camera_ocr_settle_sec": 0.16,
            "camera_ocr_detector_box_expand": 1.20,
            "camera_ocr_use_worker": True,
            "camera_ocr_use_detector_box": True,
            "camera_ocr_upscale_enabled": True,
            "camera_ocr_enhance_enabled": True,
            "camera_dump_ocr_input_enabled": False,
            "camera_dump_ocr_input_only": False,
            "camera_debug_ocr_enabled": False,
            "enable_detector_fallback": True,
            "enable_small_plate_rescue": True,
            "ocr_second_pass_7char_enabled": True,
        })
        logger.info("Perfil aplicado: jetson-production")
        return

    if profile == "jetson-realtime":
        config.update({
            "yolo_imgsz": 320,
            "camera_detection_stride": 8,
            "camera_adaptive_stride_enabled": True,
            "camera_adaptive_stride_target_fps": 9.0,
            "camera_adaptive_stride_update_sec": 2.0,
            "camera_adaptive_stride_min": 5,
            "camera_adaptive_stride_max": 14,
            "camera_motion_skip_enabled": True,
            "camera_motion_skip_threshold": 1.1,
            "camera_motion_skip_max_frames": 10,
            "camera_small_rescue_every_n_detections": 4,
            "camera_small_rescue_only_when_no_live": True,
            "camera_preview_width": 416,
            "camera_display_width": 640,
            "camera_ocr_cooldown_sec": 1.4,
            "camera_ocr_max_pending": 1,
            "camera_ocr_settle_sec": 0.20,
            "camera_ocr_detector_box_expand": 1.20,
            "camera_ocr_use_worker": True,
            "camera_ocr_use_detector_box": True,
            "camera_ocr_upscale_enabled": True,
            "camera_ocr_enhance_enabled": True,
            "camera_ocr_temporal_vote_enabled": True,
            "camera_ocr_vote_window": 4,
            "camera_ocr_vote_min_hits": 2,
            "camera_ocr_vote_max_age_sec": 4.0,
            "camera_ocr_vote_force_accept_conf": 0.72,
            "camera_plate_capture_enabled": True,
            "camera_plate_capture_dir": "outputs/plate_captures",
            "camera_plate_capture_cooldown_sec": 2.0,
            "camera_plate_capture_same_text_cooldown_sec": 6.0,
            "camera_plate_capture_min_ocr_conf": 0.50,
            "camera_plate_capture_include_ocr_box": True,
            "camera_dump_ocr_input_enabled": False,
            "camera_dump_ocr_input_only": False,
            "camera_debug_ocr_enabled": False,
            "enable_detector_fallback": False,
            "enable_small_plate_rescue": True,
            "small_plate_rescue_only_on_miss": True,
            "small_plate_rescue_upscale": 1.5,
            "small_plate_rescue_imgsz": 640,
            "small_plate_rescue_conf": 0.10,
            "small_plate_rescue_accept_conf": 0.22,
            "small_plate_rescue_tiling": False,
            "ocr_second_pass_7char_enabled": True,
        })
        logger.info("Perfil aplicado: jetson-realtime")
        return

    logger.warning("Perfil desconocido: %s. Se mantiene configuración actual.", profile_name)
